---
- name: configuration
  hosts: all
  gather_facts: false
  become: true

  tasks: 
  - name: Configure repositories
  - include_role: 
    name: commons

  - name: Deploy HAProxy
  - include_role: 
    name: frontends

  - name: Deploy Tomcat
  - include_role: 
    name: apps

  - name: Deploy PostgreSQL
  - include_role:
    name: appdbs
