---
- hosts: all
  gather_facts: false
  roles:
    - role: 'roles/commons'

- hosts: frontends
  gather_facts: false
  roles: 
    - role: 'roles/frontends'

- hosts: apps
  gather_facts: false
  roles: 
    - role: 'roles/apps'

- hosts: appdbs
  gather_facts: false
  roles: 
    - role: 'roles/appdbs'

# db check or create -> module command create