- yum:
    name: postgresql-server
    state: latest

- service:
    name: postgresql
    enabled: yes

- shell: |
    postgresql-setup initdb
  ignore_errors: yes

- service:
    name: postgresql.service
    state: started
