- yum:
    name: postgresql-server
    state: latest

- service:
    name: postgresql
    enabled: yes

- shell: |
    postgresql-11-setup initdb
  ignore_errors: yes
  
# only run the next 2 tasks once!
#  - name: initilize postgres
#    command: postgresql-setup initdb
#  - name: initilize postgres some more
#    command: chkconfig postgresql on
- service:
    name: postgresql.service
    state: started
