- name: deploy haproxy
  hosts: frontends
  gather_facts: false # remove later! speeds up testing
  become: true

  tasks:
  - name: install http and HAProxy 
    yum:
      name: 
      - httpie
      - haproxy
      state: latest

  - name: enable HAProxy service
    service:
      name: haproxy
      enabled: yes
  - name: configure haproxy
    template:
      src: ./haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
  - name: restart HAproxy
    service:
      name: haproxy
      state: restarted
