- yum:
    name: 
    - httpie
    - haproxy
    state: latest

- service:
    name: haproxy
    enabled: yes
    
- template:
    src: ./haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- service:
    name: haproxy
    state: restarted
