- yum:
    name: 
      - tomcat
      - httpd  
    state: latest

- service:
    name: tomcat
    enabled: yes

- service:
    name: httpd
    enabled: yes    

- file:
      path: /usr/share/tomcat/webapps/ansible
      state: directory
- template:
    src: index.html.j2
    dest: /usr/share/tomcat/webapps/ansible/index.html
    mode: 0644

- service:
    name: tomcat
    state: started

- service:
    name: httpd
    state: started
